theme: minima

title: Sockfeet Research

# Your name to show in the footer
author: Sockfeet Research

description: Experimentation in agency

url: "https://www.sockfeetresearch.com"
baseurl: ""

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax