title: Sockfeet Research
url: "https://www.sockfeetresearch.com"
baseurl: ""   # ‚Üê empty!

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
=======
# markdown: kramdown
# kramdown:
#   math_engine: mathjax
# permalink: /:year/:title:output_ext
